"""Drop association tables

Revision ID: 27eb63df548c
Revises: 575d1a697e08
Create Date: 2025-07-15 08:37:17.267731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27eb63df548c"
down_revision: Union[str, None] = "575d1a697e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("brand_category")
    op.drop_table("product_group_category")
    op.drop_table("product_category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_category",
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("product_category_category_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("product_category_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "category_id", name=op.f("product_category_pkey")
        ),
    )
    op.create_table(
        "product_group_category",
        sa.Column("product_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("product_group_category_category_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_group_id"],
            ["product_groups.id"],
            name=op.f("product_group_category_product_group_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "product_group_id", "category_id", name=op.f("product_group_category_pkey")
        ),
    )
    op.create_table(
        "brand_category",
        sa.Column("brand_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("brand_category_brand_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("brand_category_category_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "brand_id", "category_id", name=op.f("brand_category_pkey")
        ),
    )
    # ### end Alembic commands ###
