"""add category columns

Revision ID: 3e69479bdd6a
Revises: 27eb63df548c
Create Date: 2025-07-15 08:53:48.040758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e69479bdd6a'
down_revision: Union[str, None] = '27eb63df548c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_groups', sa.Column('category_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_product_groups_category'), table_name='product_groups')
    op.create_foreign_key(None, 'product_groups', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('product_groups', 'category')
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.add_column('product_groups', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_groups', type_='foreignkey')
    op.create_index(op.f('ix_product_groups_category'), 'product_groups', ['category'], unique=False)
    op.drop_column('product_groups', 'category_id')
    # ### end Alembic commands ###
