"""add category columns

Revision ID: 5760b3da00ab
Revises: 3e69479bdd6a
Create Date: 2025-07-15 12:11:47.957691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5760b3da00ab"
down_revision: Union[str, None] = "3e69479bdd6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_groups", sa.Column("organization_id", sa.UUID(), nullable=False)
    )
    op.alter_column(
        "product_groups", "category_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(
        op.f("product_groups_category_id_fkey"), "product_groups", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "product_groups",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "product_groups",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("products", sa.Column("organization_id", sa.UUID(), nullable=False))
    op.alter_column(
        "products", "product_group_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column("products", "category_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(
        op.f("products_category_id_fkey"), "products", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "products",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "products", "categories", ["category_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        op.f("products_category_id_fkey"),
        "products",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("products", "category_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "products", "product_group_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("products", "organization_id")
    op.drop_constraint(None, "product_groups", type_="foreignkey")
    op.drop_constraint(None, "product_groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("product_groups_category_id_fkey"),
        "product_groups",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "product_groups", "category_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("product_groups", "organization_id")
    # ### end Alembic commands ###
