"""Add host field to api_usage_metrics

Revision ID: 7976c22ca41e
Revises: fc9724858b4a
Create Date: 2025-07-30 20:07:25.165530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7976c22ca41e'
down_revision: Union[str, None] = 'fc9724858b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_usage_metrics', sa.Column('host', sa.String(length=255), nullable=True))
    op.alter_column('api_usage_metrics', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_usage_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_api_usage_request_id'), table_name='api_usage_metrics')
    op.create_index('idx_api_usage_host_timestamp', 'api_usage_metrics', ['host', 'timestamp'], unique=False)
    op.create_index(op.f('ix_api_usage_metrics_request_id'), 'api_usage_metrics', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_metrics_request_id'), table_name='api_usage_metrics')
    op.drop_index('idx_api_usage_host_timestamp', table_name='api_usage_metrics')
    op.create_index(op.f('idx_api_usage_request_id'), 'api_usage_metrics', ['request_id'], unique=False)
    op.alter_column('api_usage_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_usage_metrics', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_column('api_usage_metrics', 'host')
    # ### end Alembic commands ###
