"""Add domain field to organizations table

Revision ID: 7cc8136a45a3
Revises: bbf0012ca55f
Create Date: 2025-07-29 20:36:37.768199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc8136a45a3'
down_revision: Union[str, None] = 'bbf0012ca55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('domain', sa.String(), nullable=True, comment='Custom domain configured by seller (e.g., agent.brand.com)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'domain')
    # ### end Alembic commands ###
